name: Actions
on: workflow_dispatch

jobs:
 print:
   runs-on: macos-latest
   steps: 
   - name: Print to console 
     run: echo hellow GitHub Actions
   - name: Print a few lines
     run: | 
      echo First line!
      echo Second line! 
